version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV_VAR_NAME=value
    networks:
      - deploy_network
    container_name: backend

  frontend-test:
    build:
      context: ./frontend-test
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8501:8501"
    networks:
      - deploy_network
    container_name: frontend-test

networks:
  deploy_network:
    driver: bridge
